ALTER TYPE "NSTPComponentType" ADD VALUE IF NOT EXISTS 'CWTS_COASTGUARD';
ALTER TYPE "NSTPComponentType" ADD VALUE IF NOT EXISTS 'CWTS_SUNDAY';
ALTER TYPE "NSTPComponentType" ADD VALUE IF NOT EXISTS 'MTS';
