export type {
  BiliranMunicipality,
  ComponentApplicationState,
  NstpAccount,
  NstpAssessment,
  NstpComponent,
  NstpGradeRecord,
  NstpModule,
  NstpQuestion,
  NstpRole,
  NstpStudent,
  NstpTrainingGroup,
  PendingStudentRegistration,
  QualifyingExamResult,
} from '../data/nstpData';
