import { exportXlsxWorkbook, type SpreadsheetCell, type SpreadsheetSheet } from './spreadsheetExport';

export type ExportFormat = 'xlsx' | 'csv' | 'pdf' | 'print';

export type ExportColumn<T> = {
  header: string;
  value: keyof T | ((row: T, index: number) => SpreadsheetCell);
  width?: number;
};

export type ExportMetadata = {
  title: string;
  dataType: string;
  scope?: string;
  generatedBy?: string;
  filters?: Record<string, SpreadsheetCell>;
  institution?: string;
  systemName?: string;
  signatureLines?: string[];
};

export type ExportAuditEntry = {
  id: string;
  dataType: string;
  format: ExportFormat;
  scope: string;
  generatedBy: string;
  filters: Record<string, SpreadsheetCell>;
  rowCount: number;
  exportedAt: string;
};

const EXPORT_AUDIT_KEY = 'nstp-export-audit-log';

const today = () => new Date().toISOString().slice(0, 10);

const sanitizeFilenamePart = (value: string) => (
  value
    .replace(/[^\w\s.-]/g, ' ')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    || 'All'
);

const escapeHtml = (value: SpreadsheetCell) => String(value ?? '').replace(/[&<>"']/g, (character) => ({
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
}[character] || character));

export function buildNSTPExportFilename(dataType: string, scope = 'All', extension: ExportFormat | 'xlsx' = 'xlsx') {
  return `NSTP_${sanitizeFilenamePart(dataType)}_${sanitizeFilenamePart(scope)}_${today()}.${extension === 'print' ? 'pdf' : extension}`;
}

export function loadExportAuditLog(): ExportAuditEntry[] {
  try {
    const parsed = JSON.parse(localStorage.getItem(EXPORT_AUDIT_KEY) || '[]');
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function recordExportAudit(metadata: ExportMetadata, format: ExportFormat, rowCount: number) {
  const entry: ExportAuditEntry = {
    id: `export-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    dataType: metadata.dataType,
    format,
    scope: metadata.scope || 'All',
    generatedBy: metadata.generatedBy || 'System user',
    filters: metadata.filters || {},
    rowCount,
    exportedAt: new Date().toISOString(),
  };
  localStorage.setItem(EXPORT_AUDIT_KEY, JSON.stringify([entry, ...loadExportAuditLog()].slice(0, 200)));
}

const resolveValue = <T,>(row: T, column: ExportColumn<T>, index: number): SpreadsheetCell => (
  typeof column.value === 'function' ? column.value(row, index) : row[column.value] as SpreadsheetCell
);

export function rowsForExport<T>(rows: T[], columns: ExportColumn<T>[]) {
  return rows.map((row, index) => columns.map((column) => resolveValue(row, column, index)));
}

const downloadTextFile = (filename: string, content: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};

export function exportRowsCsv<T>(rows: T[], columns: ExportColumn<T>[], metadata: ExportMetadata) {
  if (!rows.length) throw new Error('No rows are available for export.');
  const csvRows = [
    columns.map((column) => column.header),
    ...rowsForExport(rows, columns),
  ].map((row) => row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','));
  const filename = buildNSTPExportFilename(metadata.dataType, metadata.scope, 'csv');
  downloadTextFile(filename, `\ufeff${csvRows.join('\n')}`, 'text/csv;charset=utf-8;');
  recordExportAudit(metadata, 'csv', rows.length);
}

const metadataRows = (metadata: ExportMetadata): SpreadsheetCell[][] => {
  const filters = Object.entries(metadata.filters || {});
  return [
    ['Institution', metadata.institution || 'Biliran Province State University'],
    ['System', metadata.systemName || 'NSTP Management System'],
    ['Report', metadata.title],
    ['Generated', new Date().toLocaleString()],
    ['Generated By', metadata.generatedBy || 'System user'],
    ['Scope', metadata.scope || 'All'],
    ...(filters.length ? filters.map(([key, value]) => [`Filter: ${key}`, value]) : [['Filters', 'None']]),
  ];
};

export function exportRowsXlsx<T>(rows: T[], columns: ExportColumn<T>[], metadata: ExportMetadata, extraSheets: SpreadsheetSheet[] = []) {
  if (!rows.length && !extraSheets.length) throw new Error('No rows are available for export.');
  const filename = buildNSTPExportFilename(metadata.dataType, metadata.scope, 'xlsx');
  exportXlsxWorkbook(filename, [
    {
      name: 'Summary',
      rows: metadataRows(metadata),
      columnWidths: [24, 42],
    },
    {
      name: metadata.dataType,
      rows: [columns.map((column) => column.header), ...rowsForExport(rows, columns)],
      columnWidths: columns.map((column) => column.width || Math.max(12, column.header.length + 2)),
    },
    ...extraSheets,
  ]);
  recordExportAudit(metadata, 'xlsx', rows.length);
}

export async function exportRowsPdf<T>(rows: T[], columns: ExportColumn<T>[], metadata: ExportMetadata) {
  if (!rows.length) throw new Error('No rows are available for export.');
  const [{ default: JsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const doc = new JsPDF({ orientation: columns.length > 6 ? 'landscape' : 'portrait' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const generated = new Date().toLocaleString();
  const filters = Object.entries(metadata.filters || {});

  doc.setFontSize(13);
  doc.text(metadata.institution || 'Biliran Province State University', 14, 14);
  doc.setFontSize(10);
  doc.text(metadata.systemName || 'NSTP Management System', 14, 20);
  doc.setFontSize(15);
  doc.text(metadata.title, 14, 31);
  doc.setFontSize(9);
  doc.text(`Generated: ${generated}`, 14, 38);
  doc.text(`Generated by: ${metadata.generatedBy || 'System user'}`, 14, 43);
  doc.text(`Scope: ${metadata.scope || 'All'}`, 14, 48);
  doc.text(`Filters: ${filters.length ? filters.map(([key, value]) => `${key}: ${value ?? 'All'}`).join(' | ') : 'None'}`, 14, 53, { maxWidth: pageWidth - 28 });

  autoTable(doc, {
    startY: 62,
    head: [columns.map((column) => column.header)],
    body: rowsForExport(rows, columns).map((row) => row.map((cell) => String(cell ?? ''))),
    styles: { fontSize: columns.length > 8 ? 7 : 8, cellPadding: 2 },
    headStyles: { fillColor: [29, 78, 216] },
    didDrawPage: () => {
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.text(`Page ${doc.getCurrentPageInfo().pageNumber} of ${pageCount}`, pageWidth - 32, doc.internal.pageSize.getHeight() - 10);
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 70;
  if (metadata.signatureLines?.length) {
    let signatureY = Math.min(doc.internal.pageSize.getHeight() - 35, finalY + 22);
    if (signatureY < finalY + 16) {
      doc.addPage();
      signatureY = 48;
    }
    metadata.signatureLines.slice(0, 3).forEach((label, index) => {
      const x = 24 + index * 82;
      doc.line(x, signatureY, x + 58, signatureY);
      doc.text(label, x, signatureY + 5);
    });
  }

  doc.save(buildNSTPExportFilename(metadata.dataType, metadata.scope, 'pdf'));
  recordExportAudit(metadata, 'pdf', rows.length);
}

export function printRows<T>(rows: T[], columns: ExportColumn<T>[], metadata: ExportMetadata) {
  if (!rows.length) throw new Error('No rows are available for export.');
  const filters = Object.entries(metadata.filters || {});
  const popup = window.open('', '_blank', 'noopener,noreferrer,width=1100,height=760');
  if (!popup) throw new Error('Print window was blocked by the browser.');
  popup.document.write(`<!doctype html><html><head><title>${escapeHtml(metadata.title)}</title><style>
    @page { margin: 18mm; }
    body { color: #172033; font-family: Arial, sans-serif; font-size: 12px; }
    h1, h2, p { margin: 0; }
    header { border-bottom: 2px solid #1d4ed8; margin-bottom: 16px; padding-bottom: 12px; }
    h1 { font-size: 18px; margin-top: 8px; }
    .meta { color: #475569; display: grid; gap: 4px; margin-top: 10px; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #cbd5e1; padding: 7px; text-align: left; vertical-align: top; }
    th { background: #eaf1ff; color: #173b8f; font-size: 11px; text-transform: uppercase; }
    .signatures { display: flex; gap: 36px; margin-top: 48px; }
    .sig { border-top: 1px solid #334155; min-width: 190px; padding-top: 6px; text-align: center; }
    .no-print { margin-bottom: 14px; }
    @media print { .no-print { display: none; } }
  </style></head><body>
    <button class="no-print" onclick="window.print()" style="padding:10px 14px;border:1px solid #1d4ed8;background:#1d4ed8;color:white;border-radius:8px;font-weight:700;">Print Report</button>
    <header>
      <p>${escapeHtml(metadata.institution || 'Biliran Province State University')}</p>
      <p>${escapeHtml(metadata.systemName || 'NSTP Management System')}</p>
      <h1>${escapeHtml(metadata.title)}</h1>
      <div class="meta">
        <span>Generated: ${escapeHtml(new Date().toLocaleString())}</span>
        <span>Generated by: ${escapeHtml(metadata.generatedBy || 'System user')}</span>
        <span>Scope: ${escapeHtml(metadata.scope || 'All')}</span>
        <span>Filters: ${escapeHtml(filters.length ? filters.map(([key, value]) => `${key}: ${value ?? 'All'}`).join(' | ') : 'None')}</span>
      </div>
    </header>
    <table><thead><tr>${columns.map((column) => `<th>${escapeHtml(column.header)}</th>`).join('')}</tr></thead><tbody>${rowsForExport(rows, columns).map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>
    ${metadata.signatureLines?.length ? `<div class="signatures">${metadata.signatureLines.map((label) => `<div class="sig">${escapeHtml(label)}</div>`).join('')}</div>` : ''}
  </body></html>`);
  popup.document.close();
  popup.focus();
  recordExportAudit(metadata, 'print', rows.length);
}

export async function exportRows<T>(format: ExportFormat, rows: T[], columns: ExportColumn<T>[], metadata: ExportMetadata, extraSheets: SpreadsheetSheet[] = []) {
  if (format === 'xlsx') return exportRowsXlsx(rows, columns, metadata, extraSheets);
  if (format === 'csv') return exportRowsCsv(rows, columns, metadata);
  if (format === 'pdf') return exportRowsPdf(rows, columns, metadata);
  return printRows(rows, columns, metadata);
}
